"""Claude Code export adapter — generates CLAUDE.md from .agent/ context."""

from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger(__name__)

_AGENT_FILES = [
    ("ARCHITECTURE.md", "Architecture"),
    ("STYLE.md", "Style Guide"),
    ("TESTING.md", "Testing Strategy"),
    ("PHILOSOPHY.md", "Philosophy"),
    ("STATUS.md", "Current Status"),
]


class ClaudeExportAdapter:
    """Generates a CLAUDE.md file from the project's .agent/ context.

    Concatenates all .agent/ files into a single document formatted
    for Claude Code's context ingestion.
    """

    def export(self, project_root: Path) -> str:
        """Generate CLAUDE.md content from .agent/ files.

        Args:
            project_root: Path to the project root.

        Returns:
            The complete CLAUDE.md content as a string.
        """
        agent_dir = project_root / ".agent"
        parts: list[str] = [
            "# CLAUDE.md\n\n",
            "> Auto-generated by Gemstack. Regenerate with: `gemstack export --format claude`\n\n",
            "This file contains the complete project context for Claude Code.\n\n",
        ]

        for filename, section_title in _AGENT_FILES:
            path = agent_dir / filename
            if path.exists():
                try:
                    content = path.read_text().strip()
                    parts.append(f"## {section_title}\n\n{content}\n\n---\n\n")
                except OSError as e:
                    logger.warning(f"Failed to read {path}: {e}")

        return "".join(parts)
