"""Cursor export adapter — generates .cursorrules from .agent/ context."""

from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger(__name__)

# Files to include and their section headers for .cursorrules
_AGENT_FILES = [
    ("ARCHITECTURE.md", "Architecture"),
    ("STYLE.md", "Style Guide"),
    ("TESTING.md", "Testing Strategy"),
    ("PHILOSOPHY.md", "Philosophy"),
]


class CursorExportAdapter:
    """Generates a .cursorrules file from the project's .agent/ context.

    Concatenates all .agent/ files into a single document formatted
    for Cursor's rules engine.
    """

    def export(self, project_root: Path) -> str:
        """Generate .cursorrules content from .agent/ files.

        Args:
            project_root: Path to the project root.

        Returns:
            The complete .cursorrules content as a string.
        """
        agent_dir = project_root / ".agent"
        parts: list[str] = [
            "# Project Rules (Auto-generated by Gemstack)\n",
            "# Do not edit directly — regenerate with: gemstack export --format cursor\n\n",
        ]

        for filename, section_title in _AGENT_FILES:
            path = agent_dir / filename
            if path.exists():
                try:
                    content = path.read_text().strip()
                    parts.append(f"## {section_title}\n\n{content}\n\n---\n\n")
                except OSError as e:
                    logger.warning(f"Failed to read {path}: {e}")

        return "".join(parts)
