"""Cursor export adapter — generates .cursorrules from .agent/ context."""

from __future__ import annotations

import logging
from pathlib import Path

from gemstack.adapters.base import read_agent_context

logger = logging.getLogger(__name__)

# Files to include and their section headers for .cursorrules
_AGENT_FILES = [
    ("ARCHITECTURE.md", "Architecture"),
    ("STYLE.md", "Style Guide"),
    ("TESTING.md", "Testing Strategy"),
    ("PHILOSOPHY.md", "Philosophy"),
]


class CursorExportAdapter:
    """Generates a .cursorrules file from the project's .agent/ context.

    Concatenates all .agent/ files into a single document formatted
    for Cursor's rules engine.
    """

    def export(self, project_root: Path) -> str:
        """Generate .cursorrules content from .agent/ files.

        Args:
            project_root: Path to the project root.

        Returns:
            The complete .cursorrules content as a string.
        """
        parts = [
            "# Project Rules (Auto-generated by Gemstack)\n",
            "# Do not edit directly — regenerate with: gemstack export --format cursor\n\n",
        ]

        parts.append(read_agent_context(project_root, _AGENT_FILES))

        return "".join(parts)
