"""Gemini CLI export adapter — generates GEMINI.md from .agent/ context."""

from __future__ import annotations

import logging
from pathlib import Path

from gemstack.adapters.base import read_agent_context

logger = logging.getLogger(__name__)

_AGENT_FILES = [
    ("ARCHITECTURE.md", "Architecture"),
    ("STYLE.md", "Style Guide"),
    ("TESTING.md", "Testing Strategy"),
    ("PHILOSOPHY.md", "Philosophy"),
    ("STATUS.md", "Current Status"),
]


class GeminiExportAdapter:
    """Generates a GEMINI.md file from the project's .agent/ context.

    Concatenates all .agent/ files into a single document formatted
    for Gemini CLI's context ingestion.
    """

    def export(self, project_root: Path) -> str:
        """Generate GEMINI.md content from .agent/ files.

        Args:
            project_root: Path to the project root.

        Returns:
            The complete GEMINI.md content as a string.
        """
        parts = [
            "# GEMINI.md\n\n",
            "> Auto-generated by Gemstack. Regenerate with: `gemstack export --format gemini`\n\n",
            "This file contains the complete project context for Gemini CLI.\n\n",
        ]

        parts.append(read_agent_context(project_root, _AGENT_FILES))

        return "".join(parts)
