"""gemstack ci — CI/CD configuration generation."""

from __future__ import annotations

from pathlib import Path

import typer
from rich.console import Console

from gemstack.utils.fileutil import write_atomic

console = Console()

ci_app = typer.Typer(name="ci", help="CI/CD configuration generation")

_GITHUB_ACTIONS_TEMPLATE = """\
# Generated by: gemstack ci github-actions
name: Gemstack Check

on:
  pull_request:
    branches: [main, master]

permissions:
  contents: read

jobs:
  gemstack-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install gemstack
        run: pip install gemstack
      - name: Validate .agent/ integrity
        run: gemstack check
      - name: Check for stubs
        run: |
          if grep -rn "TODO: remove stub" --include="*.py" --include="*.ts" --include="*.go" .; then
            echo "❌ Stubs found — remove before merging"
            exit 1
          fi
      - name: Verify audit findings cleared
        run: |
          if [ -s ".agent/AUDIT_FINDINGS.md" ]; then
            echo "❌ AUDIT_FINDINGS.md is not empty"
            exit 1
          fi
"""

_GITLAB_CI_TEMPLATE = """\
# Generated by: gemstack ci gitlab-ci
gemstack-check:
  image: python:3.12-slim
  stage: test
  before_script:
    - pip install gemstack
  script:
    - gemstack check
    - |
      if grep -rn "TODO: remove stub" --include="*.py" --include="*.ts" --include="*.go" .; then
        echo "❌ Stubs found — remove before merging"
        exit 1
      fi
    - |
      if [ -s ".agent/AUDIT_FINDINGS.md" ]; then
        echo "❌ AUDIT_FINDINGS.md is not empty"
        exit 1
      fi
  only:
    - merge_requests
"""


@ci_app.command("github-actions")
def github_actions(
    output: Path = typer.Option(
        ".github/workflows/gemstack.yml",
        "--output",
        "-o",
        help="Output path for the workflow file",
    ),
) -> None:
    """Generate a GitHub Actions workflow for Gemstack compliance."""
    output = output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    write_atomic(output, _GITHUB_ACTIONS_TEMPLATE)
    console.print(f"[green]✅ Created {output}[/green]")
    console.print("[dim]This workflow runs `gemstack check` on every PR.[/dim]")


@ci_app.command("gitlab-ci")
def gitlab_ci(
    output: Path = typer.Option(
        ".gitlab-ci-gemstack.yml",
        "--output",
        "-o",
        help="Output path for the CI snippet",
    ),
) -> None:
    """Generate a GitLab CI snippet for Gemstack compliance."""
    output = output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    write_atomic(output, _GITLAB_CI_TEMPLATE)
    console.print(f"[green]✅ Created {output}[/green]")
    console.print("[dim]Merge this into your .gitlab-ci.yml.[/dim]")
